pipeline:
  name: "Simple Test Pipeline"
  version: "1.0.0"
  description: "Minimal test pipeline to debug issues"
  
  plugins:
    # Source: Read simple test data
    - name: "TestSource"
      type: "DelimitedSource.DelimitedSourcePlugin"
      assembly: "C:\\source\\FlowEngine\\plugins\\DelimitedSource\\bin\\Release\\net8.0\\DelimitedSource.dll"
      config:
        FilePath: "C:\\source\\FlowEngine\\examples\\data\\simple-test.csv"
        HasHeaders: true
        Delimiter: ","
        ChunkSize: 10
        Encoding: "UTF-8"
        InferSchema: false
        OutputSchema:
          Name: "SimpleTestData"
          Description: "Simple test data schema"
          Columns:
            - Name: "customer_id"
              Type: "Integer"
              Index: 0
              IsNullable: false
            - Name: "first_name"
              Type: "String"
              Index: 1
              IsNullable: false
            - Name: "last_name"
              Type: "String"
              Index: 2
              IsNullable: false
            - Name: "age"
              Type: "Integer"
              Index: 3
              IsNullable: false
            - Name: "email"
              Type: "String"
              Index: 4
              IsNullable: false
            - Name: "account_value"
              Type: "Decimal"
              Index: 5
              IsNullable: false
        SkipMalformedRows: false
        MaxErrors: 0
        
    # Sink: Write simple output
    - name: "TestOutput"
      type: "DelimitedSink.DelimitedSinkPlugin"
      assembly: "C:\\source\\FlowEngine\\plugins\\DelimitedSink\\bin\\Release\\net8.0\\DelimitedSink.dll"
      config:
        FilePath: "C:\\source\\FlowEngine\\examples\\output\\simple-test-output.csv"
        HasHeaders: true
        Delimiter: ","
        Encoding: "UTF-8"
        BufferSize: 8192
        FlushInterval: 1000
        CreateDirectory: true
        OverwriteExisting: true
        
  connections:
    # Direct connection from source to sink
    - from: "TestSource"
      to: "TestOutput"
      channel:
        bufferSize: 100
        backpressureThreshold: 75
        fullMode: "Wait"
        timeoutSeconds: 30

  settings:
    defaultChannel:
      bufferSize: 100
      backpressureThreshold: 80
      fullMode: "Wait"
      timeoutSeconds: 30
    
    monitoring:
      enableMetrics: true
      metricsIntervalSeconds: 5
      enableTracing: true
      custom:
        logLevel: "Information"