pipeline:
  name: "Simple Pipeline Example"
  version: "1.0.0"
  description: "Basic CSV read and write with automatic schema inference"
  
  plugins:
    # Source: Read customer data from CSV file
    - name: "CustomerSource"
      type: "DelimitedSource"
      config:
        FilePath: "C:\\source\\FlowEngine\\examples\\data\\customers.csv"
        HasHeaders: true
        Delimiter: ","
        ChunkSize: 1000
        Encoding: "UTF-8"
        InferSchema: false
        OutputSchema:
          Name: "CustomerData"
          Description: "Customer information schema"
          Columns:
            - Name: "customer_id"
              Type: "Integer"
              Index: 0
              IsNullable: false
            - Name: "first_name"
              Type: "String"
              Index: 1
              IsNullable: false
            - Name: "last_name"
              Type: "String"
              Index: 2
              IsNullable: false
            - Name: "age"
              Type: "Integer"
              Index: 3
              IsNullable: false
            - Name: "email"
              Type: "String"
              Index: 4
              IsNullable: false
            - Name: "account_value"
              Type: "Decimal"
              Index: 5
              IsNullable: false
        SkipMalformedRows: true
        MaxErrors: 5
        
    # Sink: Write data to CSV file (direct passthrough)
    - name: "CustomerOutput"
      type: "DelimitedSink"
      config:
        FilePath: "C:\\source\\FlowEngine\\examples\\output\\simple-output.csv"
        HasHeaders: true
        Delimiter: ","
        Encoding: "UTF-8"
        BufferSize: 8192
        FlushInterval: 500
        CreateDirectory: true
        OverwriteExisting: true
        
  connections:
    # Direct connection from source to sink
    - from: "CustomerSource"
      to: "CustomerOutput"
      channel:
        bufferSize: 1000
        backpressureThreshold: 75
        fullMode: "Wait"
        timeoutSeconds: 30

  settings:
    defaultChannel:
      bufferSize: 1000
      backpressureThreshold: 80
      fullMode: "Wait"
      timeoutSeconds: 30
    
    monitoring:
      enableMetrics: true
      metricsIntervalSeconds: 5
      enableTracing: false
      custom:
        logLevel: "Information"
        
    custom:
      performance:
        maxConcurrentPlugins: 2
        memoryLimitMB: 256
        gcPressureThreshold: 0.8
        
      errorHandling:
        maxRetries: 1
        retryDelaySeconds: 1
        stopOnError: true
        logErrors: true