pipeline:
  name: "Test Customer Processing Pipeline"
  version: "1.0.0"
  description: "Basic test pipeline that generates customer data, enriches it, and outputs to console"
  
  plugins:
    - name: "DataSource"
      type: "FlowEngine.Core.Plugins.Examples.DataGeneratorPlugin"
      assembly: "FlowEngine.Core.dll"
      config:
        rowCount: 50
        batchSize: 10
        delayMs: 100
      
    - name: "Enrichment"
      type: "FlowEngine.Core.Plugins.Examples.DataEnrichmentPlugin"
      assembly: "FlowEngine.Core.dll"
      config:
        addSalaryBand: true
        addFullName: true
        addEmailDomain: true
        addAgeCategory: true
        
    - name: "ConsoleOutput"
      type: "FlowEngine.Core.Plugins.Examples.ConsoleOutputPlugin"
      assembly: "FlowEngine.Core.dll"
      config:
        showHeaders: true
        showRowNumbers: true
        maxRows: 25
        delimiter: " | "
        maxColumnWidth: 20
        showSummary: true
  
  connections:
    - from: "DataSource"
      to: "Enrichment"
      channel:
        bufferSize: 500
        backpressureThreshold: 80
        fullMode: "Wait"
        timeoutSeconds: 30
        
    - from: "Enrichment"  
      to: "ConsoleOutput"
      channel:
        bufferSize: 200
        backpressureThreshold: 70
        fullMode: "Wait"
        timeoutSeconds: 30

  settings:
    defaultChannel:
      bufferSize: 1000
      backpressureThreshold: 80
      fullMode: "Wait"
      timeoutSeconds: 30
    
    monitoring:
      enableMetrics: true
      metricsIntervalSeconds: 5
      enableTracing: false