pipeline:
  name: "Provider Discovery Test"
  description: "Simple pipeline to test provider discovery and validation"

  plugins:
    - name: "TestSource"
      type: "DelimitedSource"
      config:
        FilePath: "examples/data/customers-20k.csv"
        Delimiter: ","
        HasHeaders: true
        Encoding: "UTF-8"
        OutputSchema:
          Name: "CustomerData"
          Description: "Customer information schema"
          Columns:
            - Name: "customer_id"
              Type: "int32"
              Index: 0
            - Name: "first_name"
              Type: "string"
              Index: 1
            - Name: "last_name"
              Type: "string"
              Index: 2
            - Name: "age"
              Type: "int32"
              Index: 3
            - Name: "email"
              Type: "string"
              Index: 4
            - Name: "account_value"
              Type: "decimal"
              Index: 5

    - name: "TestSink"  
      type: "DelimitedSink"
      config:
        FilePath: "examples/output/test-discovery.csv"
        Delimiter: ","
        HasHeaders: true
        BufferSize: 8192
        FlushInterval: 1000
        OverwriteExisting: true

  connections:
    - from: "TestSource"
      to: "TestSink"