pipeline:
  name: "V8 Performance Benchmark"
  version: "1.0.0"
  description: "Simple V8 performance measurement"
  
  plugins:
    - name: "Source"
      type: "DelimitedSource"
      config:
        FilePath: "C:\\source\\FlowEngine\\examples\\data\\customers-20k.csv"
        HasHeaders: true
        Delimiter: ","
        ChunkSize: 500
        Encoding: "UTF-8"
        InferSchema: false
        OutputSchema:
          Name: "Customer"
          Columns:
            - Name: "ID"
              Type: "String"
              Index: 0
            - Name: "Name"
              Type: "String"
              Index: 1
            - Name: "Email"
              Type: "String"
              Index: 2

    - name: "V8Transform"
      type: "JavaScriptTransform"
      config:
        Script: |
          function process(context) {
              var name = context.input.getValue('Name') || 'Unknown';
              var email = context.input.getValue('Email') || '';
              
              context.output.setField('ProcessedName', name.toUpperCase());
              context.output.setField('Domain', email.split('@')[1] || 'no-domain');
              context.output.setField('Timestamp', new Date().toISOString());
              
              return true;
          }
        
        OutputSchema:
          Fields:
            - Name: "ProcessedName"
              Type: "string"
              Required: true
            - Name: "Domain"
              Type: "string"
              Required: true
            - Name: "Timestamp"
              Type: "string"
              Required: true

        Performance:
          EnableMonitoring: true
          TargetThroughput: 8000
          LogPerformanceWarnings: true

    - name: "Sink"
      type: "DelimitedSink"
      config:
        FilePath: "C:\\source\\FlowEngine\\examples\\output\\v8-benchmark.csv"
        HasHeaders: true
        Delimiter: ","
        Overwrite: true